name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Nuitka
      run: |
        python -m nuitka --standalone --onefile --output-dir=dist/ --enable-plugin=pyside6 --include-package=app --windows-console-mode=disable main_ui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffxiv-patcher
        path: dist/main_ui.exe
